version: '3'
services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '8888:80'

  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'

  opencart:
    image: docker.io/bitnami/opencart:3
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=192.168.0.3:8081
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
      - phpadmin

  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    volumes:
      - "/Users/dsharando/.aerokube/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/Users/dsharando/.aerokube/selenoid/video:/opt/selenoid/video"
      - "/Users/dsharando/.aerokube/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/dsharando/PycharmProjects/python-qa-engineer/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - '4444:4444'

  tests:
    container_name: tests
    build:
      dockerfile: Dockerfile
      context:  .
    depends_on:
      - opencart
      - selenoid

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
